---
system_name: 'lens_system2'

band:
  - 'F390W'

pixel_size : 0.04

model:
  lens:
    - 'EPL' # the first mass profile needs to be for the deflector as required by `lenstronomy`
    - 'SHEAR_GAMMA_PSI'
  lens_light:
    - 'SERSIC_ELLIPSE'
  source_light:
    - 'SHAPELETS'

lens_option:
  centroid_init: [0.04, -0.04]

lens_light_option:
  fix: {0: {'n_sersic': 4.}} # fix n_sersic to 4. for 0-th light profile

source_light_option:
  n_max: [4] # array with n_max for each band

fitting:
  pso: true
  pso_settings:
    num_particle: 20
    num_iteration: 50

  sampling: true
  sampler: emcee
  sampler_settings: # keywords to be sent to lenstronomy.Workflow.fitting_sequence.FittingSequence.mcmc()
    n_burn : 0
    n_run: 100
    walkerRatio: 2

numeric_option:
  supersampling_factor: [2]